# LogSumExp Reasoning
https://en.wikipedia.org/wiki/LogSumExp


https://lingpipe-blog.com/2012/02/16/howprevent-overflow-underflow-logistic-regression/


numerical computation deep learning book

https://github.com/udacity/deep-learning/blob/master/semi-supervised/semi-supervised_learning_2_solution.ipynb

In [1]:
import numpy as np

In [2]:
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x))

def softmax_safe(x):
    return np.exp(x-np.max(x))/np.sum(np.exp(x-np.max(x)))

def logsumexp(arr):
    return np.log(np.sum(np.exp(arr)))

def logsumexp_safe(arr):
    return np.max(arr) + np.log(np.sum(np.exp(arr - np.max(arr))))

def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def sigmoid_inv(x):
    return np.log(x/(1-x))

In [3]:
sigmoid_inv(sigmoid(0.5))

0.5000000000000001

In [4]:
x = np.array([0.2,0.8])
#x = np.log(x)
np.exp(x - logsumexp(x))

array([0.35434369, 0.64565631])

In [5]:
np.log(np.exp(1))

1.0

In [6]:
#No extra class
class_logits = np.array([1,2, 1.6, 0.7])*(10)

real_class_logits = class_logits
fake_class_logits = 0.

gan_logits = logsumexp_safe(real_class_logits)

out = softmax_safe(class_logits)

print(class_logits)
print(real_class_logits)
print(fake_class_logits)
print(gan_logits)
print(out)
print(sigmoid(gan_logits))

[10. 20. 16.  7.]
[10. 20. 16.  7.]
0.0
20.018196729854324
[4.45812706e-05 9.81967831e-01 1.79853682e-02 2.21957077e-06]
0.9999999979760135


In [36]:
#Extra class
class_logits = np.array([1,2, 1.6, 0.7, -0.0])
num_classes = 4

real_class_logits, fake_class_logits = np.split(class_logits, [num_classes])
assert fake_class_logits.shape[0] == 1, fake_class_logits.shape
fake_class_logits = np.squeeze(fake_class_logits)

gan_logits = logsumexp_safe(real_class_logits) - fake_class_logits

gan_logits2 = sigmoid_inv(1 - np.exp(fake_class_logits)/np.sum(np.exp(class_logits)))


p = (np.sum(np.exp(class_logits)) - np.exp(fake_class_logits))/np.sum(np.exp(class_logits))

aux1 = np.sum(np.exp(class_logits))
aux2 = np.exp(fake_class_logits)

one_minus_p = aux2/aux1


SOLVED!


gan_logits3 = np.log(p) - np.log(one_minus_p)

#gan_logits4 = sigmoid_inv((np.sum(np.exp(class_logits)) - np.exp(fake_class_logits))/np.sum(np.exp(class_logits)))

#out = softmax_safe(class_logits)

#print(class_logits)
#print(real_class_logits)
#print(fake_class_logits)
print("GANLOGIT", gan_logits)
print("GANLOGIT2", gan_logits3)
#print("OUT", out)
#print(sigmoid(gan_logits))

#print("RL", real_class_logits.sum())


sigmoid(gan_logits) + out[-1]

GANLOGIT 2.837564045968448
GANLOGIT2 2.837564045968448


0.9446745006700173

In [16]:
x0 = np.array([1,2,3,4])

np.log(1-np.exp(x0[3])/np.sum(np.exp(x0)))

-1.032583734116815

In [17]:
np.log(-10)

C:\Users\du0x\Anaconda2\envs\tf\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


nan

In [22]:
logsumexp_safe(x)

1.2374879504858858

In [63]:
a = np.array([1,0.5,2,4])

In [65]:
s = softmax(a)
fake_prob = s[3]
print(fake_prob)
print(1-fake_prob)

0.822828734841
0.177171265159


In [66]:
real_logit = np.log(np.sum(np.exp(a-np.max(a)))) + np.max(a) - a[3]
real_logit

0.19500719857359439

In [67]:
sigmoid(real_logit)

0.54859789122588909

In [48]:
np.log(np.sum(np.exp(a)))

9.0011147287934943